//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2Referencial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MvcDatabaseEntities5 : DbContext
    {
        public MvcDatabaseEntities5()
            : base("name=MvcDatabaseEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleTable> RoleTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }

        public virtual ObjectResult<RoleUserConnect> ValidateUser(string TUsername, string TPassword)
        {
            var usernameParameter = TUsername != null ?
                new ObjectParameter("Username", TUsername) :
                new ObjectParameter("Username", typeof(string));

            var passwordParameter = TPassword != null ?
                new ObjectParameter("Password", TPassword) :
                new ObjectParameter("Password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RoleUserConnect>("ValidateUser", usernameParameter, passwordParameter);
        }
    }

   
}
