//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2Referencial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public int Tid { get; set; }
        public string Tname { get; set; }
        public byte[] Tprofile { get; set; }
        public Nullable<int> TDomainid { get; set; }
    
        public virtual Training Training { get; set; }
    }
}
