//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2Referencial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int TUserid { get; set; }
        public string TUsername { get; set; }
        public Nullable<int> TRoleid { get; set; }
        public string TPassword { get; set; }
    
        public virtual RoleTable RoleTable { get; set; }
    }
}
